# Install pre-commit hooks via
# pre-commit install

exclude: >
    (?x)^(
      \.vscode/settings\.json|
      docs/conf\.py|
    )$

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-added-large-files
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-yaml
    - id: destroyed-symlinks
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: sort-simple-yaml
    - id: trailing-whitespace
